export const items= [
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#Hong1535",productPrice:1.24,productFavorite:35,productThumbnailUrl:'https://lh3.googleusercontent.com/MmtavcUNNiTpLFfDqqol8pwp1_TKSEv0AbkKSxmN2lffhgYtkxAdfAo72lZVSJ4hpRW87s9TCL-HYMEIpaJ8PdgWBQWVlPsMZkgM6A=w305'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#ghe23434",productPrice:1.35,productFavorite:43,productThumbnailUrl:'https://lh3.googleusercontent.com/qGLA-qtTThUV063ueH3gLxZgm0pC1VKusEYh7BrOUi8hBMAbssWvv2Vt0oRTdsWO51CDCkvF5Lc93fC62iI_liTxKz1H2qYyQxnRfg=w352'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#ghe254334",productPrice:1.2,productFavorite:24,productThumbnailUrl:'https://lh3.googleusercontent.com/3usYOjVkwnra66EAhX4yJB-xmYCfFoTsREGVvVLCYWhtVG4pifdZLBRCSgv6wbjbV4rwPamlBDgganvgFO3xeifJyZQtqxwTYpXiqtc=w300'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#Hong1535",productPrice:1.24,productFavorite:35,productThumbnailUrl:'https://lh3.googleusercontent.com/EdzzR4e6tc8jtOsRZ7T5-d9ejmy6r7zyulAjw4D-XlNMNISRPAwYXpVLOmj_dL-gWme69VvlDBj_EsXit8jwSFPjS_oFvgcjmo-Z=w328'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#ghe23434",productPrice:1.35,productFavorite:43,productThumbnailUrl:'https://lh3.googleusercontent.com/qeCj7NRekCZ9BUjM8c9Pk02DxmPgX483qgEkVJeLXYIDOFVTXAfCg8TTztcMMQPgYFsNDUqndF5asWPCgJVpiM6P39VzpWa3TTKrvg=w300'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#ghe254334",productPrice:1.2,productFavorite:24,productThumbnailUrl:'https://lh3.googleusercontent.com/jWonBwIV3RRzCv2xEu3pKA5buXUne_vnltLcLIfnluPuctdbTd-ScsBO94-njkA2L5VHVRA56CG5tbbxwacCvFdFWaZzuIJNUB1sVCA=w300'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#g53434",productPrice:1.37,productFavorite:52,productThumbnailUrl:'https://lh3.googleusercontent.com/Op3TUf8vqznY1geantykLx86mlGf4yEaBfKT25utQlQu8keA9ywYdwYYzVSqGZG_3uSJKCNcUBAVK6qs520xhZ6lsP3dVDGsM9wnRA=w352'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#Hong1535",productPrice:1.24,productFavorite:35,productThumbnailUrl:'https://lh3.googleusercontent.com/jc4P6pZhiNsBNxErAilpkx-d3RZDpNpJbYjs2k5nou29DJGe_r27tu2i0xy0KBOIgHaQhgVOqIF4-aLpjIqLV6eo-IsIUQ98VI_jDw=w300'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#ghe23434",productPrice:1.35,productFavorite:43,productThumbnailUrl:'https://lh3.googleusercontent.com/qGLA-qtTThUV063ueH3gLxZgm0pC1VKusEYh7BrOUi8hBMAbssWvv2Vt0oRTdsWO51CDCkvF5Lc93fC62iI_liTxKz1H2qYyQxnRfg=w352'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#g53434",productPrice:1.37,productFavorite:52,productThumbnailUrl:'https://lh3.googleusercontent.com/Op3TUf8vqznY1geantykLx86mlGf4yEaBfKT25utQlQu8keA9ywYdwYYzVSqGZG_3uSJKCNcUBAVK6qs520xhZ6lsP3dVDGsM9wnRA=w352'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#ghe254334",productPrice:1.2,productFavorite:24,productThumbnailUrl:'https://lh3.googleusercontent.com/BqScg3QwKPcNW_cxtvBws2D2cE8Us-QsN9yYmB_8UzUikBwLfOC5Nc2JgXWOB2ijx4lAU2KcYplGujimb2FUD9ArixBFeCyNPcES=w352'},
  {productRegDt:[2022,3,21,18,13,6],productCode:0,productTitle:"#g53434",productPrice:1.37,productFavorite:52,productThumbnailUrl:'https://lh3.googleusercontent.com/OjwqOOt3_po4pPlTYg43Us9_pp4Ji9X8JKZY4aCsjzHISKQL-u2oSX_q4NmK5qZZn5PPYfMCpDS8OKFXBzXzXA6ljfWfaxGdEvc8DA=w300'},
]
export interface ItemType{
  item:{
    productTitle: string,
    productPrice: Number,
    productThumbnailUrl: string,
    productFavorite: Number,
    productRegDt:Object,
    productCode: Number,
  },
  artist:{
    "authId": Number,
    "followeeCnt": Number,
    "followerCnt": Number,
    "userAddress": String,
    "userDescription": String,
    "userEmail": String,
    "userEmailConfirm": Boolean,
    "userId": Number,
    "userImgUrl": String,
    "userNick": String,
    "userRole": String
  },
  itemdetail:{
    productId: Number,
    userId: Number,
    productTitle: string,
    productDesc: string,
    productCode: Number,
    productXCoordinate: Number,
    productYCoordinate: Number,
    productView: Boolean,
    productState: Number,
    productPrice: Number,
    productRegDt: string,
    productFileUrl: string,
    productThumbnailUrl: string,
    favoriteCount: Number
  },
}
export const itemdetail = {
  "productId": 9,
  "userId": 1,
  "productTitle": "이 상품으로 말하자!!!면!!!",
  "productDesc": "상품 설명이라 함은....",
  "productCode": 1,
  "productXCoordinate": 0,
  "productYCoordinate": 0,
  "productView": false,
  "productState": 1,
  "productPrice": 0,
  "productRegDt": "2022-03-21 09:13:06",
  "productFileUrl": "https://ncity-bucket.s3.ap-northeast-2.amazonaws.com/302c19ef-90f1-49fa-b25c-70c4db9821f6.png",
  "productThumbnailUrl": "https://ncity-bucket.s3.ap-northeast-2.amazonaws.com/d4875988-d772-404c-b3cd-901aa561e909.png",
  "favoriteCount": 3
}
   
export const artists = [
  { 
    authId: 0,
    followeeCnt: 23,
    followerCnt: 43,
    userAddress: '0xddf2402j9fkdsjan',
    userDescription:"Happy Club is the bestHHapHappy Club is the bestHHappy Club is the bestHHappy Club is the bestHHappy Club is the bestHHappy Club is the bestHHappy Club is the bestHpy Club is the bestHHappy Club is the bestHHappy Club is the bestHappy Club is the best Club all Club all over the world. u know what? it is better to run out when i see u. cuase i'm too strong to keep ur house safe.",
    userEmail: 'limhoungho@naver.com',
    userEmailConfirm:false,
    userId: 24233,
    userImgUrl:"https://lh3.googleusercontent.com/rPB_SZcWuxqlK5M6LpQdF_-4gm3ucQ4xuS7AMjgZJk1kseF2d20Q1GTsXPQs_aOyu8iyDpwKowjw1tw1XfyJbna5oeOSJz1n3LAEQZE=w352",
    userNick:"Happy Club ",
    userRole: 'artist',
  },
  { 
    authId: 1,
    followeeCnt: 13,
    followerCnt: 233,
    userAddress: '0xddf23fkdsjan',
    userDescription:"Club is the Happy lub all ovorld. best C u ker the wnow what? it is better to run out when i see u. cuase i'm too strong to keep ur house safe.",
    userEmail: 'lim24ngho@naver.com',
    userEmailConfirm:true,
    userId: 124223,
    userImgUrl:"https://lh3.googleusercontent.com/C0K1INFhIXcsRwalRPr_3SkYpk_esO039M9veydGwcrrNFks737CZW2ZPKNNpev5oXuS68NbjTQyvw_P7J8-02Otlf5VWXSYMwYJ9w=w600",
    userNick:"Happppii",
    userRole: 'artist',
  },
  { 
    authId: 2,
    followeeCnt: 14,
    followerCnt: 63,
    userAddress: '0x23423fkdsjan',
    userDescription:"b all ovorHapp C u ld. Club st the isy lubeker the wnow what? it is better to run out when i see u. cuase i'm too strong to keep ur house safe.",
    userEmail: 'l214gho@naver.com',
    userEmailConfirm:true,
    userId: 1223,
    userImgUrl:"https://lh3.googleusercontent.com/snLRz1QWBbKRRsNEuLZUxVdEf_-FQY9fCCqyDOpEJ9jptyir_X2D-l5p7DbAIg_0_4NapUwIqGok13RQ_GIlKPCVCRhacgHfJXRDpQ=w361",
    userNick:"Happ23i",
    userRole: 'artist',
  },
  { 
    authId: 3,
    followeeCnt: 53,
    followerCnt: 233,
    userAddress: '0x23422dsjan',
    userDescription:"the isy lubeker the  lub st .ovorHapp C u ldb all Cwnow what? it is better to run out when i see u. cuase i'm too strong to keep ur house safe.",
    userEmail: 'l223o@naver.com',
    userEmailConfirm:false,
    userId: 12253,
    userImgUrl:"https://lh3.googleusercontent.com/NaifflZNmeVEOduBMjid9-g5ZZiAQl3nucODNOyoNw8aLz4a3GIJapZOyamAAvIrZzt7PEqo3O1tGb--m7Xk8OYjstLycvtYXNhkLQ=w361",
    userNick:"sad",
    userRole: 'artist',
  },
  { 
    authId: 4,
    followeeCnt: 13,
    followerCnt: 53,
    userAddress: '0x2344232dsjan',
    userDescription:" st .ovorHapp C u lthr the  lubdb all Ce isy lubekewnow what? it is better to run out when i see u. cuase i'm too strong to keep ur house safe.",
    userEmail: 'l22asdfvo@naver.com',
    userEmailConfirm:true,
    userId: 153,
    userImgUrl:"https://lh3.googleusercontent.com/2DST2_ggsZYUnunVfpwFwtOfPZC6YG1aoZMLb0jSDb6Myl_sTMn5luzeN1zi6LVjh-lymRyWC-AXzGxa9td6_xDe1ckJ1UDLdwbx3as=w361",
    userNick:"sad55",
    userRole: 'artist',
  }
]